# Generated by Django 2.1.1 on 2018-09-22 17:53

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_auto_20180921_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='logo',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/joabeluz/workspace/ygks/media'), upload_to='member_logos'),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/joabeluz/workspace/ygks/media'), upload_to='member_logos'),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='image',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/joabeluz/workspace/ygks/media'), upload_to='stamp_files'),
        ),
    ]
