# Generated by Django 2.1.1 on 2018-09-22 18:55

from django.db import migrations
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_auto_20180922_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='icon',
            field=fontawesome.fields.IconField(blank=True, max_length=60),
        ),
    ]
