# Generated by Django 2.1.1 on 2018-09-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_sector_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
