# Generated by Django 2.1.1 on 2018-09-25 20:27

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_member_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='member',
            name='longitude',
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True),
        ),
    ]
